### ISSUE TITLE
read length setting cannot work

### ISSUE THREAD

**Issue by JavenCao** [mdcao/capsim#3]
Hi,

I am using CapSim with the following commands:

jsa.sim.capsim --reference ucsc.hg19.fasta \
      --probe chr11_chr16_rescue_probe.bam \
	  --ID test_id \
	  --miseq test_miseq \
	  --fmedian 500 \
	  --illen 100 \
	  --num 5000

log file is as follows:
[main] INFO japsa.tools.bio.sim.SimulateCaptureCmd - Mark capturable regions
[main] INFO japsa.tools.bio.sim.SimulateCaptureCmd - Generated 7661 selected 5000; reject1 = 2; reject2 = 340; reject3 = 2319; reject4 = 0
Parameters for simulation
           reference = ucsc.hg19.fasta
               probe = chr11_chr16_rescue_probe.bam
             logFile = -
                  ID = test_id
               miseq = test_miseq
              pacbio = (null)
             fmedian = 500
              fshape = 6.0
                 num = 5000
               pblen = 30000
               illen = 100
                seed = 0
                help = false
#Seed 2019171277
Read 93 chr 3137161264bp

**However, the simulated reads are all with a read length of 250. And it remains 250bp whatever I changed the illen to 50,100, et. al.**

Below is a simulated reads of 250bp in length:
@test_id_chr16_244488_245154
GTACCTGGCTTAAATGCCATCCTTGAACATCACCTTAAAGGTGTCCATCCATGTGTGCCCTGCTTCAGACACAGGATGAGCATGGGTGAAAGTTTAGAGCTGGAGATACCAGTCACCCAGCTCTGCATACTTTCCGTGCCCTTGTGGGGAGCGTGCTCTCATCCACACTGGGTATGGAAGATTATCCTTATGCCATCGTGGCTCTCTGGATGGAGAAGACTCGTGATTCTTTGTCTTACTGGCTCTGACT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

**Comment by c-zhou** [comment]
Hi JavenCao, 

Thanks for your enquiry. I guess you downloaded japsa from the release https://github.com/mdcao/japsa/releases/tag/v1.7-10a. However, this release is not fully functioning for CapSim. You can use either `git clone https://github.com/mdcao/japsa.git` or `wget https://github.com/mdcao/japsa/archive/master.zip` to download the latest japsa and reinstall it and this will probably solve the problem. Sorry for the confusion.

**Comment by JavenCao** [comment]
Thank you for your kindly reply.

Following your instruction, I git cloned the japsa.git. However, I got the following errors. Can you give more guidence? Thank you and regards.

**$make install INSTALL_DIR=/paedwy/disk1/yjcao/software/JASPA/japsa**
javac -sourcepath src/main/java -cp target/main-classes::libs/colloquial.jar:libs/commons-io-2.5.jar:libs/commons-math3-3.0.jar:libs/jhdf5.jar:libs/jhdfobj.jar:libs/htsjdk-2.10.1.jar:libs/guava-18.0.jar:libs/jcommon-1.0.23.jar:libs/jfreechart-1.0.19.jar:libs/gs-core-1.3.jar:libs/gs-ui-1.3.jar:libs/gs-algo-1.3.jar:libs/javax.json-api-1.0.jar:libs/javax.json-1.0.4.jar:libs/slf4j-api-1.7.25.jar:libs/slf4j-simple-1.7.25.jar:libs/jfxrt.jar:libs/gson-2.3.jar -nowarn -d target/main-classes  src/main/java/./japsa/bio/hts/SpeciesMixtureIdenfication.java
src/main/java/japsa/bio/np/MultinomialCI.java:93: error: unmappable character for encoding ASCII
                   // mom es global y se usa fuera de esta funci??n
                                                                ^
src/main/java/japsa/bio/np/MultinomialCI.java:93: error: unmappable character for encoding ASCII
                   // mom es global y se usa fuera de esta funci??n
                                                                 ^
2 errors
make: *** [target/main-classes/./japsa/bio/hts/SpeciesMixtureIdenfication.class] Error 1

**Comment by c-zhou** [comment]
It looks like your platform has a different encoding system.  Try to run `export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` before compiling japsa.
